## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Katie Scranton"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Personal website"
  logo = "images/10.jpeg"
  favicon = false

